apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
stringData:
  username: "PLACEHOLDER_MONGODB_USERNAME"  # Substitua pelo username real
  password: "PLACEHOLDER_MONGODB_PASSWORD"  # Substitua pela senha real

# ATENÇÃO: Este é apenas um TEMPLATE e não deve ser aplicado diretamente.
# Para criar o secret real:
# 
# 1. Substitua os placeholders acima pelos valores reais
# 2. Use o kubectl para criar o secret:
#
# kubectl apply -f mongodb-secret.yaml
#
# OU crie manualmente com:
#
# kubectl create secret generic mongodb-secret \
#   --namespace=mongodb \
#   --from-literal=username='seu_username_real' \
#   --from-literal=password='sua_senha_real' 