apiVersion: v1
kind: Secret
metadata:
  name: urbana-connect-openai
  namespace: urbana-connect
type: Opaque
stringData:
  OPENAI_API_KEY: "PLACEHOLDER_OPENAI_API_KEY"

# ATENÇÃO: Este é apenas um TEMPLATE e não deve ser aplicado diretamente.
# Para criar o secret real:
# 
# 1. Substitua o placeholder acima pela chave real da API OpenAI
# 2. Use o kubectl para criar o secret:
#
# kubectl apply -f openai-secret.yaml
#
# OU crie manualmente com:
#
# kubectl create secret generic urbana-connect-openai \
#   --namespace=urbana-connect \
#   --from-literal=OPENAI_API_KEY='sua_chave_api_openai_real' 