apiVersion: v1
kind: Secret
metadata:
  name: do-registry-credentials
  namespace: urbana-connect
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.digitalocean.com": {
          "username": "PLACEHOLDER_DO_REGISTRY_USERNAME",
          "password": "PLACEHOLDER_DO_REGISTRY_PASSWORD",
          "auth": "PLACEHOLDER_DO_REGISTRY_AUTH"
        }
      }
    }

# ATENÇÃO: Este é apenas um TEMPLATE e não deve ser aplicado diretamente.
# Para criar o secret real:
# 
# 1. Substitua os placeholders acima pelos valores reais
# 2. Use o kubectl para criar o secret:
#
# kubectl apply -f registry-secret.yaml
#
# OU crie manualmente com:
#
# kubectl create secret docker-registry do-registry-credentials \
#   --namespace=urbana-connect \
#   --docker-server=registry.digitalocean.com \
#   --docker-username=seu_username \
#   --docker-password=seu_password 