apiVersion: v1
kind: Secret
metadata:
  name: urbana-connect-whatsapp
  namespace: urbana-connect
type: Opaque
stringData:
  WHATSAPP_PHONE_NUMBER_ID: "PLACEHOLDER_WHATSAPP_PHONE_NUMBER_ID"
  WHATSAPP_ACCESS_TOKEN: "PLACEHOLDER_WHATSAPP_ACCESS_TOKEN"
  WHATSAPP_VERIFY_TOKEN: "PLACEHOLDER_WHATSAPP_VERIFY_TOKEN"

# ATENÇÃO: Este é apenas um TEMPLATE e não deve ser aplicado diretamente.
# Para criar o secret real:
# 
# 1. Substitua os placeholders acima pelos valores reais
# 2. Use o kubectl para criar o secret:
#
# kubectl apply -f whatsapp-secret.yaml
#
# OU crie manualmente com:
#
# kubectl create secret generic urbana-connect-whatsapp \
#   --namespace=urbana-connect \
#   --from-literal=WHATSAPP_PHONE_NUMBER_ID='seu_phone_number_id_real' \
#   --from-literal=WHATSAPP_ACCESS_TOKEN='seu_access_token_real' \
#   --from-literal=WHATSAPP_VERIFY_TOKEN='seu_verify_token_real' 