# Informações do projeto
sonar.projectKey=urbana-do-brasil_urbana-connect
sonar.organization=urbana-do-brasil
sonar.projectName=urbana-connect
sonar.projectVersion=0.0.1-SNAPSHOT

# Código-fonte e testes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.java.source=21
sonar.sourceEncoding=UTF-8

# Cobertura JaCoCo
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Exclusões
sonar.exclusions=\
  **/*Application.java,\
  **/config/**
