apiVersion: v1
kind: Secret
metadata:
  name: urbana-connect-mongodb-uri
  namespace: urbana-connect-hml
type: Opaque
stringData:
  MONGODB_URI: "mongodb://PLACEHOLDER_MONGODB_USERNAME:PLACEHOLDER_MONGODB_PASSWORD@urbana-connect-mongodb.urbana-connect-hml.svc.cluster.local:27017/urbana-connect?authSource=admin&replicaSet=rs0&retryWrites=true&retryReads=true&w=majority"

# Template para a URI consumida pela aplicação.
