apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Substitua pelo seu endereço de e-mail
    email: emanuel.guimaraes@urbanadobrasil.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Nome do Secret que armazenará a chave privada da conta ACME
      name: letsencrypt-prod-account-key
    # Configuração do desafio HTTP01
    solvers:
    - http01:
        ingress:
          class: nginx 