package br.com.urbana.connect.domain.conversation.model;

public enum ConversationContentKey {
    GREETING_TEXT,
    DIRECT_TRIAGE_TEXT,
    GUIDED_TRIAGE_PROMPT,
    PLAYBOOK_GREETING,
    PLAYBOOK_ICP_QUALIFICATION,
    PLAYBOOK_SERVICE_DISCOVERY,
    TERMS_TEXT,
    PAYMENT_METHOD_TEXT,
    CLOSING_TEXT,
    HUMAN_HANDOFF_ACK,
    FALLBACK_UNKNOWN_INPUT
}
