services:
  mongodb:
    image: mongo:latest
    container_name: urbana-connect-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=urbana-connect
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/urbana-connect --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  wiremock:
    image: wiremock/wiremock:3.13.0
    container_name: urbana-connect-wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./src/test/resources/wiremock:/home/wiremock
    command: ["--verbose"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    name: urbana-connect-mongodb-data 