version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: urbana-connect-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=urbana-connect
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/urbana-connect --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  mongo-express:
    image: mongo-express:latest
    container_name: urbana-connect-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=senha123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
    name: urbana-connect-mongodb-data 