apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: staging
data:
  SPRING_PROFILES_ACTIVE: "staging"
  DATABASE_URL: "jdbc:postgresql://postgres-staging:5432/app_db"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_SEUDOMINIO: "DEBUG"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus" 