apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urbana-connect-hml-platform-local
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - mongodb.yaml
  - mongodb-rs-init-job.yaml
  - api.yaml
  - networkpolicy.yaml
