apiVersion: v1
kind: ServiceAccount
metadata:
  name: hml-platform-local-runtime
  labels:
    app.kubernetes.io/part-of: urbana-connect-hml-platform-local
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hml-platform-local-init
  labels:
    app.kubernetes.io/part-of: urbana-connect-hml-platform-local
automountServiceAccountToken: false
