{
  "k3d": "v5.9.0",
  "k3s": {
    "version": "v1.36.4+k3s1",
    "image": "docker.io/rancher/k3s:v1.36.4-k3s1@sha256:edad48e12bf81c3a09ac1c05c0c0ffaaa22145980b989d6fae84543a76b83657"
  },
  "kubectl": {
    "gitVersion": "v1.36.1",
    "kustomizeVersion": "v5.8.1"
  }
}
