apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urbana-connect-hml

resources:
  - namespace.yaml
  - ingress.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/urbana-do-brasil/urbana-connect
    newTag: hml-523eb5fab49cf8ba1813c0ce90c436ccd64f39f9
