apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urbana-connect-hml

resources:
  - namespace.yaml
  - ingress.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/urbana-do-brasil/urbana-connect
    newTag: hml-c0bd67996e1cdf625bc57f28f45a701fded13774
