name: Build, Test e Análise de Qualidade

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write  # Necessário para que o SonarCloud comente nos PRs
  checks: write         # Necessário para publicar status de qualidade

jobs:
  build_test_analyze:
    name: Build, Test e Análise
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # SonarCloud precisa do histórico completo para algumas métricas

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Garantir permissão de execução para gradlew
      run: chmod +x ./gradlew
      working-directory: ./app

    - name: Build e teste com Gradle
      run: ./gradlew build jacocoTestReport
      working-directory: ./app
      
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Análise SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: app

    - name: Publicar resultados de testes
      uses: actions/upload-artifact@v4
      if: always()  # Executa mesmo se passos anteriores falharem
      with:
        name: test-results
        path: app/build/reports/tests/
        
    - name: Publicar relatório de cobertura
      uses: actions/upload-artifact@v4
      if: always()  # Executa mesmo se passos anteriores falharem
      with:
        name: coverage-report
        path: app/build/reports/jacoco/test/html/ 