name: Deploy para Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão da imagem a ser implantada (formato: X.Y.Z)'
        required: true
        default: '1.0.0'
        type: string

jobs:
  deploy:
    name: Deploy para DOKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configurar KUBECONFIG
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Atualizar imagem no Deployment Kubernetes
      run: |
        kubectl set image deployment/urbana-connect urbana-connect=registry.digitalocean.com/urbana-connect-registry/urbana-connect:${{ inputs.version }} -n urbana-connect

    - name: Verificar status do rollout
      run: |
        kubectl rollout status deployment/urbana-connect -n urbana-connect --timeout=180s 